backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
  
collections:
  - name: "menu"
    label: "Menu"
    folder: "_data/meun"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Price (Toman)", name: "price", widget: "number"}